In [1]:
from job_env import JOB_env

In [2]:
env = JOB_env(debug_index=0)

In [3]:
env.queries[0]

({'chn': 'char_name',
  'ci': 'cast_info',
  'cn': 'company_name',
  'ct': 'company_type',
  'mc': 'movie_companies',
  'rt': 'role_type',
  't': 'title'},
 [['t.id', 'mc.movie_id'],
  ['t.id', 'ci.movie_id'],
  ['ci.movie_id', 'mc.movie_id'],
  ['chn.id', 'ci.person_role_id'],
  ['rt.id', 'ci.role_id'],
  ['cn.id', 'mc.company_id'],
  ['ct.id', 'mc.company_type_id']])

In [4]:
env.all_cardinalities[0]

{'name': 'cluster2b_5 avg',
 'relations': [{'name': 'chn',
   'basetable': 'char_name',
   'cardinality': 3140340.0,
   'unfilteredCardinality': 3140340.0},
  {'name': 'ci',
   'basetable': 'cast_info',
   'cardinality': 32288,
   'unfilteredCardinality': 36244300.0},
  {'name': 'cn',
   'basetable': 'company_name',
   'cardinality': 1361,
   'unfilteredCardinality': 234997},
  {'name': 'ct',
   'basetable': 'company_type',
   'cardinality': 4,
   'unfilteredCardinality': 4},
  {'name': 'mc',
   'basetable': 'movie_companies',
   'cardinality': 2609130.0,
   'unfilteredCardinality': 2609130.0},
  {'name': 'rt',
   'basetable': 'role_type',
   'cardinality': 1,
   'unfilteredCardinality': 12},
  {'name': 't',
   'basetable': 'title',
   'cardinality': 1012920.0,
   'unfilteredCardinality': 2528310.0}],
 'joins': [{'relations': ['chn', 'ci'], 'primaryKeySide': 'chn'},
  {'relations': ['ci', 'mc']},
  {'relations': ['cn', 'mc'], 'primaryKeySide': 'cn'},
  {'relations': ['ct', 'mc'], 'prim

In [5]:
env.all_cardinalities[0]['relations'][0]

{'name': 'chn',
 'basetable': 'char_name',
 'cardinality': 3140340.0,
 'unfilteredCardinality': 3140340.0}

In [6]:
env.reset()

Restart from 10a.


({'tables': [(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    3140340.0),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
    32288),
   (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
    2609130.0),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
    1012920.0)],
  'possible_actions': {(4,
    6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
   (1,
    6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
  

In [7]:
env.state['tables']

[(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  3140340.0),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
  32288),
 (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  1361),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
  2609130.0),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
  1012920.0)]

In [8]:
env.state['possible_actions'].keys()

dict_keys([(4, 6), (1, 6), (1, 4), (0, 1), (1, 5), (2, 4), (3, 4)])

In [ ]:
[key for key in env.table_mapping.keys()]

In [ ]:
env.tables

In [ ]:
env.predicates

In [ ]:
print(len(env.predicates))
print(len(list(env.state['possible_actions'].keys())))

In [ ]:
len(env.cardinalities['sizes'])

In [ ]:
import numpy as np
np.zeros(3,dtype=int)

In [10]:
env.step((4,6))

({'tables': [(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    3140340.0),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
    32288),
   (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]),
    829639)],
  'possible_actions': {(1,
    5): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
   (0,
    1): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [11]:
env.state['possible_actions'].keys()

dict_keys([(1, 5), (0, 1), (1, 4), (2, 5), (3, 5)])

In [12]:
env.step((1,5))

({'tables': [(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    3140340.0),
   (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    20369)],
  'possible_actions': {(0,
    4): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
   (3,
    4): (array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])),
   (1,
 

In [13]:
env.state['possible_actions'].keys()

dict_keys([(0, 4), (3, 4), (1, 4), (2, 4)])

In [14]:
env.step((0,4))

({'tables': [(array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    18771)],
  'possible_actions': {(2,
    3): (array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])),
   (0,
    3): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])),
   (1,
    3): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           

In [15]:
env.state['possible_actions'].keys()

dict_keys([(2, 3), (0, 3), (1, 3)])

In [16]:
env.step((2,3))

({'tables': [(array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    13694)],
  'possible_actions': {(0,
    2): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])),
   (1,
    2): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))}},
 -9.524713059681009,
 False,
 None)

In [17]:
env.state['possible_actions'].keys()

dict_keys([(0, 2), (1, 2)])

In [18]:
env.step((0,2))

({'tables': [(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    4),
   (array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    104)],
  'possible_actions': {(0,
    1): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))}},
 -4.6443908991413725,
 False,
 None)

In [19]:
env.state['possible_actions'].keys()

dict_keys([(0, 1)])

In [20]:
env.step((0,1))

({'tables': [(array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    104)],
  'possible_actions': None},
 -4.6443908991413725,
 True,
 None)