In [1]:
from job_env import JOB_env

In [2]:
env = JOB_env(debug_index=0)

In [3]:
env.queries[0]

({'chn': 'char_name',
  'ci': 'cast_info',
  'cn': 'company_name',
  'ct': 'company_type',
  'mc': 'movie_companies',
  'rt': 'role_type',
  't': 'title'},
 [['t.id', 'mc.movie_id'],
  ['t.id', 'ci.movie_id'],
  ['ci.movie_id', 'mc.movie_id'],
  ['chn.id', 'ci.person_role_id'],
  ['rt.id', 'ci.role_id'],
  ['cn.id', 'mc.company_id'],
  ['ct.id', 'mc.company_type_id']])

In [4]:
env.all_cardinalities[0]

{'name': 'cluster2b_5 avg',
 'relations': [{'name': 'chn',
   'basetable': 'char_name',
   'cardinality': 3140340.0,
   'unfilteredCardinality': 3140340.0},
  {'name': 'ci',
   'basetable': 'cast_info',
   'cardinality': 32288,
   'unfilteredCardinality': 36244300.0},
  {'name': 'cn',
   'basetable': 'company_name',
   'cardinality': 1361,
   'unfilteredCardinality': 234997},
  {'name': 'ct',
   'basetable': 'company_type',
   'cardinality': 4,
   'unfilteredCardinality': 4},
  {'name': 'mc',
   'basetable': 'movie_companies',
   'cardinality': 2609130.0,
   'unfilteredCardinality': 2609130.0},
  {'name': 'rt',
   'basetable': 'role_type',
   'cardinality': 1,
   'unfilteredCardinality': 12},
  {'name': 't',
   'basetable': 'title',
   'cardinality': 1012920.0,
   'unfilteredCardinality': 2528310.0}],
 'joins': [{'relations': ['chn', 'ci'], 'primaryKeySide': 'chn'},
  {'relations': ['ci', 'mc']},
  {'relations': ['cn', 'mc'], 'primaryKeySide': 'cn'},
  {'relations': ['ct', 'mc'], 'prim

In [ ]:
env.all_cardinalities[0]['relations'][0]

In [5]:
#print(env.job_list)
env.debug_index=env.job_list.index('1a')
env.reset()

Restart from 1a.


({'tables': [(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
    28889),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1380040.0),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
    2528310.0)],
  'possible_actions': {(0,
    2): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
   (2,
    4): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),

In [44]:
env.state['tables']

[(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]), 1),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
  28889),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  1380040.0),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
  2528310.0)]

In [45]:
env.state['possible_actions'].keys()

dict_keys([(0, 2), (2, 4), (3, 4), (2, 3), (1, 3)])

In [46]:
[key for key in env.table_mapping.keys()]

['ct', 'it', 'mc', 'mi_idx', 't']

In [47]:
env.tables

['ct', 'it', 'mc', 'mi_idx', 't']

In [51]:
env.predicates

[['ct.id', 'mc.company_type_id'],
 ['t.id', 'mc.movie_id'],
 ['t.id', 'mi_idx.movie_id'],
 ['mc.movie_id', 'mi_idx.movie_id'],
 ['it.id', 'mi_idx.info_type_id']]

In [12]:
print(len(env.predicates))
print(len(list(env.state['possible_actions'].keys())))

7
7


In [13]:
len(env.cardinalities['sizes'])

46

In [14]:
import numpy as np
np.zeros(3,dtype=int)

array([0, 0, 0])

In [16]:
#env.step((4,6))
print(env.naturaltable[env.index])
print(env.state["tables"])
print(env.all_tables)
print( env.table_mapping)
#env.step((11,15))
#env.step((11,15))
env.state['possible_actions'].keys()

['company_type', 'info_type', 'movie_companies', 'movie_info_idx', 'title']
[(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1), (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]), 1), (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]), 28889), (array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1380040.0), (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]), 2528310.0)]
['company_name', 'kind_type', 'char_name', 'link_type', 'keyword', 'person_info', 'movie_link', 'movie_keyword', 'movie_info_idx', 'role_type', 'name', 'company_type', 'comp_cast_type', 'aka_title', 'movie_info', 'info_type', 'title', 'cast_info', 'aka_name', 'movie_companies', 'complete_cast']
{'ct': 'company_type', 'it': 'info_type', 'mc': 'movie_companies', 'mi_idx': 'movie_info_idx', 't': 'title'}


dict_keys([(0, 2), (2, 4), (3, 4), (2, 3), (1, 3)])

In [27]:
#env.state['possible_actions'].keys()

In [12]:
#nv.step((1,5))

({'tables': [(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    3140340.0),
   (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    20369)],
  'possible_actions': {(0,
    4): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
   (3,
    4): (array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])),
   (1,
 

In [13]:
#env.state['possible_actions'].keys()

dict_keys([(0, 4), (3, 4), (1, 4), (2, 4)])

In [14]:
#env.step((0,4))

({'tables': [(array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    18771)],
  'possible_actions': {(2,
    3): (array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])),
   (0,
    3): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])),
   (1,
    3): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           

In [15]:
#env.state['possible_actions'].keys()

dict_keys([(2, 3), (0, 3), (1, 3)])

In [16]:
#env.step((2,3))

({'tables': [(array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    13694)],
  'possible_actions': {(0,
    2): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])),
   (1,
    2): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))}},
 -9.524713059681009,
 False,
 None)

In [17]:
#env.state['possible_actions'].keys()

dict_keys([(0, 2), (1, 2)])

In [18]:
#env.step((0,2))

({'tables': [(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    4),
   (array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    104)],
  'possible_actions': {(0,
    1): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))}},
 -4.6443908991413725,
 False,
 None)

In [19]:
#env.state['possible_actions'].keys()

dict_keys([(0, 1)])

In [20]:
#env.step((0,1))

({'tables': [(array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    104)],
  'possible_actions': None},
 -4.6443908991413725,
 True,
 None)

In [7]:
#env.debug_index=env.job_list.index('1a')
env.reset()

Restart from 10a.


({'tables': [(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    3140340.0),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
    32288),
   (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
    2609130.0),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
    1012920.0)],
  'possible_actions': {(4,
    6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
   (1,
    6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
  

In [17]:
import xml.etree.ElementTree as ET
import os
logx_dir="../logsx"

#merged_num=list();
def processnode(Nodelist):
            #todo = list();
            #todo.append(root);
            output= list();
            nextExec= list()
            coutput = list()
            cgroup = list();
            cgroupn = list();
            pair_group=list();
            flist = list()
            while Nodelist:
                level = Nodelist.pop()
                output.extend(level.findall("{http://www.postgresql.org/2009/explain}Alias"));
                nextExec.extend(level.findall("{http://www.postgresql.org/2009/explain}Query"));
                nextExec.extend(level.findall("{http://www.postgresql.org/2009/explain}Plan"));
                nextExec.extend(level.findall("{http://www.postgresql.org/2009/explain}Plans"));
                res =processnode(nextExec);
                #coutput.extend( rr);
                #cgroupn.extend(rt);
                if res:
                    pair_group.extend(res);
            #print (output, len(pair_group))
            #print (pair_group)
            
            if output and pair_group:
                #merge
                #print("Merging ", output ,coutput)
                temp1 =[x.text for x in output];
                #print(temp)
                #temp2 =[x.text for x in coutput];
                #print(temp)
                #print("Merging ", temp1 ,temp2)
                rtval = temp1.pop();
                flist.append(output[-1])
                cgroup.append(list(env.table_mapping.keys()).index(rtval));
                while temp1 or pair_group:
                    donator = None;
                    if temp1: 
                        donator = temp1.pop()
                        donatorsub=[list(env.table_mapping.keys()).index(donator)];
                    elif pair_group:
                        tmp = pair_group.pop()
                        donatorsub, par1 = tmp
                        print (donatorsub, par1)
                        donator= par1[0].text;
                    a=999;
                    b=9999;
                    print(cgroup)
                    print(donatorsub)
                    for t in cgroup:
                        for h in donatorsub:
                            print(t,h)
                            if (t,h) in env.state['possible_actions'].keys():
                                a=t;
                                b=h;
                                print("hit")
                            if (h,t) in env.state['possible_actions'].keys():
                                a=h;
                                b=t;
                                print("hit")    
                    
                    print("Merging ", rtval ,donator)
                    cgroup.extend(donatorsub);
                    #cgroup.append(list(env.table_mapping.keys()).index(rtval));
                    #print (list(env.table_mapping.keys()).index(donator), list(env.table_mapping.keys()).index(rtval))
                   
                    dlen= len (env.state['tables'])
                   # for x in range(dlen) :
                   #     if env.state['tables'][0][0][list(env.table_mapping.keys()).index(donator)] ==1:
                   #         a=x;
                    #for x in range(dlen):
                    #    if env.state['tables'][0][0][list(env.table_mapping.keys()).index(rtval)] ==1:
                    #        b=x;        
                    #a =list(env.table_mapping.keys()).index(donator);
                    #b=list(env.table_mapping.keys()).index(rtval)  ;
                    #a= list(env.table_mapping.keys()).index(donator);
                    #b= env.all_tables.index(env.table_mapping[rtval])
                    #b= list(env.table_mapping.keys()).index(rtval);
                    print(env.state['possible_actions'].keys())
                    #print(env.table_mapping);
                    print(a, b)
                    env.step(sorted((a,b)))
                return [(cgroup, flist)];
            if output:
                tmp =[x.text for x in output];
                #print(tmp[0])
                ret=list(env.table_mapping.keys()).index(tmp[0]);
                cgroup.append(ret);
                #print(ret)
                return [(cgroup ,output)];
            elif pair_group:
                #assert(len(pair_group) ==1)
                if len(pair_group) !=1:
                        assert(len(pair_group) ==2)
                        tmp = pair_group.pop()
                        donatorsub, par1 = tmp
                        print (donatorsub, par1)
                        donator= par1[0].text;
                        
                        tmp=pair_group.pop()
                        donatorsub2, par2 = tmp
                        print (donatorsub2, par2)
                        donator2= par2[0].text;
                        a=999;
                        b=9999;
                        print("merge", donator,donator2 )
                        for t in donatorsub2:
                                for h in donatorsub:
                                    print(t,h)
                                    if (t,h) in env.state['possible_actions'].keys():
                                        a=t;
                                        b=h;
                                        print("hit")
                                    if (h,t) in env.state['possible_actions'].keys():
                                        a=h;
                                        b=t;
                                        print("hit")  
                        donatorsub2.extend(donatorsub);
                        print(env.state['possible_actions'].keys())
                        #print(env.table_mapping);
                        print(a, b)
                        env.step(sorted((a,b)))
                        return [donatorsub2, par2];
                assert(len(pair_group) ==1)
                return pair_group;

            return None;
    
for fname in env.job_list:
            #file = open(os.path.join(query_dir, f'{fname}.sql.xml'),mode='r')
            tree = ET.parse(os.path.join(logx_dir, f'{fname}.sql.xml'))
            print(fname)
            env.debug_index=env.job_list.index(fname)
            env.reset()
            root = tree.getroot();
            #for child in root:
            #    print(child.tag, child.attrib)
            #    for cchild in child:
            #        print(cchild.tag, cchild.attrib)
            #        for ccchild in cchild:
            #            print(ccchild.tag,"xxx", ccchild.attrib)
            #level;
            donee = False
            todo = list();
            todo.append(root);
            output= list();
            output= processnode (todo)
            #temp =[x.text for x in output];
            print(output)
            #ET.
            #ET.dump(root);
            #for name in root.iter("ns0:Alias"):
            #    print(name)
            break
            #self.basejoinorder.append( Parser(file.read()).tables)
    

10a
Restart from 10a.
[2] [<Element '{http://www.postgresql.org/2009/explain}Alias' at 0x7f436e7d4b30>]
[4]
[2]
4 2
hit
Merging  mc cn
dict_keys([(4, 6), (1, 6), (1, 4), (0, 1), (1, 5), (2, 4), (3, 4)])
2 4
[4, 2] [<Element '{http://www.postgresql.org/2009/explain}Alias' at 0x7f436e7d4220>]
[1]
[4, 2]
1 4
hit
1 2
Merging  ci mc
dict_keys([(4, 5), (1, 4), (1, 5), (0, 1), (1, 3), (2, 5)])
1 4
[1, 4, 2] [<Element '{http://www.postgresql.org/2009/explain}Alias' at 0x7f436e7cdb30>]
[5] [<Element '{http://www.postgresql.org/2009/explain}Alias' at 0x7f436e7d7a90>]
merge ci rt
5 1
5 4
5 2
dict_keys([(3, 4), (0, 4), (2, 4), (1, 3)])
999 9999


IndexError: pop index out of range

In [29]:
env.table_mapping

{'chn': 'char_name',
 'ci': 'cast_info',
 'cn': 'company_name',
 'ct': 'company_type',
 'mc': 'movie_companies',
 'rt': 'role_type',
 't': 'title'}

In [67]:
env.predicates

[['ct.id', 'mc.company_type_id'],
 ['t.id', 'mc.movie_id'],
 ['t.id', 'mi_idx.movie_id'],
 ['mc.movie_id', 'mi_idx.movie_id'],
 ['it.id', 'mi_idx.info_type_id']]

In [5]:
env.all_tables

['company_name',
 'kind_type',
 'char_name',
 'link_type',
 'keyword',
 'person_info',
 'movie_link',
 'movie_keyword',
 'movie_info_idx',
 'role_type',
 'name',
 'company_type',
 'comp_cast_type',
 'aka_title',
 'movie_info',
 'info_type',
 'title',
 'cast_info',
 'aka_name',
 'movie_companies',
 'complete_cast']

In [6]:
env.state['possible_actions'].keys()

dict_keys([(4, 6), (1, 6), (1, 4), (0, 1), (1, 5), (2, 4), (3, 4)])

In [7]:
env.state['possible_actions']

{(4,
  6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
 (1,
  6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])),
 (1,
  4): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
 (0,
  1): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 

In [14]:
env.step((1,5))

({'tables': [(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    3140340.0),
   (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
    20369)],
  'possible_actions': {(0,
    4): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
   (3,
    4): (array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])),
   (1,
 

In [22]:
env.state['possible_actions'].keys()

dict_keys([(4, 6), (1, 6), (1, 4), (0, 1), (1, 5), (2, 4), (3, 4)])

In [16]:
env.table_mapping

{'chn': 'char_name',
 'ci': 'cast_info',
 'cn': 'company_name',
 'ct': 'company_type',
 'mc': 'movie_companies',
 'rt': 'role_type',
 't': 'title'}

In [17]:
env.reset()

Restart from 10a.


({'tables': [(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    3140340.0),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
    32288),
   (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    1361),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
    2609130.0),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
   (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
    1012920.0)],
  'possible_actions': {(4,
    6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
   (1,
    6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
  

In [48]:
env.state

{'tables': [(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
   3140340.0),
  (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
   32288),
  (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
   1361),
  (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
  (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
   2609130.0),
  (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
  (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
   1012920.0)],
 'possible_actions': {(4,
   6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
  (1,
   6): (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
          0, 0, 0, 0

In [38]:
env.table_mapping.keys()


dict_keys(['chn', 'ci', 'cn', 'ct', 'mc', 'rt', 't'])

In [40]:
env.tables

['chn', 'ci', 'cn', 'ct', 'mc', 'rt', 't']

In [45]:
env.state['tables'][0][0][1]

0

In [51]:
len (env.state['tables'])

7

In [54]:
env.state['tables']

[(array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  3140340.0),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
  32288),
 (array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  1361),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 4),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
  2609130.0),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
  1012920.0)]

In [62]:
 env.tables

['chn', 'ci', 'cn', 'ct', 'mc', 'rt', 't']

In [64]:
env.predicates

[['t.id', 'mc.movie_id'],
 ['t.id', 'ci.movie_id'],
 ['ci.movie_id', 'mc.movie_id'],
 ['chn.id', 'ci.person_role_id'],
 ['rt.id', 'ci.role_id'],
 ['cn.id', 'mc.company_id'],
 ['ct.id', 'mc.company_type_id']]